Метод Гаусса

In [38]:
import numpy as np

def gaussMethod(M):
    for nLine, line in enumerate(M):
        pivot = line[nLine]
        line /= pivot
        for lower_line in M[nLine+1:]:
            coeff = lower_line[nLine]
            lower_line -= coeff * line
    for nLine in range(len(M)- 1,0,-1):
        line = M[nLine]
        for upper_line in M[:nLine]:
            coeff = upper_line[nLine]
            upper_line[-1] -= coeff*line[-1]
            upper_line[nLine] = 0
    return M

A = np.array([[1, 4, 3, 10],
              [2, 1, -1, -1],
              [3, -1, 1, 11]], dtype=float)

print(gaussMethod(A)[:, -1])

[ 2. -1.  4.]


Метод прямоугольника

In [49]:
import copy
import numpy as np

def gauss_exceptions_method(M):
    matrix_size = len(M)
    
    for k in range(matrix_size):
        m_copy = copy.deepcopy(M)
        dig_el = M[k][k]
        
        for i in range(k, matrix_size):
            for j in range(matrix_size + 1):
                if i > k and j <= k:
                    M[i][j] = 0
                elif i == k:
                    M[i][j] /= dig_el
                else:
                    M[i][j] -= m_copy[k][j] * m_copy[i][k] / dig_el

    for i in range(matrix_size - 1, 0, -1):
        for upper_row in M[:i]:
            upper_row[-1] -= upper_row[i] * M[i][-1]
            upper_row[i] = 0

    return np.array(M[:, -1])

A = np.array([[1, 4, 3, 10],
              [2, 1, -1, -1],
              [3, -1, 1, 11]], dtype=float)

print(gauss_exceptions_method(A))  


[ 2. -1.  4.]


Выбор ведущего элемента

In [37]:
import numpy as np

def gaussMethod(M):
    n = len(M)
    for i in range(n):
        maxEl = abs(M[i:, i]).argmax() + i
        if maxEl != i:
            M[[i, maxEl]] = M[[maxEl, i]]
        pivot = M[i, i]
        M[i] /= pivot
        for j in range(i+1, n):
            M[j] -= M[j, i] * M[i]
    for i in range(n-1,0,-1):
        for j in range(i):
            coeff = M[j, i]
            M[j] -= coeff * M[i]
    return M

A = np.array([[0, 4, 3, 10],
              [2, 0, -1, -1],
              [3, -1, 0, 11]], dtype=float)

print(gaussMethod(A)[:, -1])


[ 2.83333333 -2.5         6.66666667]


Метод простых итераций

In [36]:
import numpy as np

def find_coeff(M):
    n, _ = M.shape
    for i in range(n):
        maxEl = abs(M[i:, i]).argmax() + i
        if maxEl != i:
            M[[i, maxEl]] = M[[maxEl, i]]
    for i in range(n):
        curr_el = M[i, i]
        M[i] /= -curr_el
        M[i, i] = 0
    A, b = M[:, :n], (-1) * M[:, n]
    return A, b

def simple_iter_method(A, b, x_0, max_iterations=100, eps=1e-6):
    for iter in range(max_iterations):
        x_k = np.dot(A, x_0) + b
        norm_vec = sum((x_k[i] - x_0[i]) ** 2 for i in range(len(x_k)))**0.5
        norm_matrix = sum((A[i, j])**2 for i in range(A.shape[0]) for j in range(A.shape[1]))**0.5
        flag = (norm_matrix*norm_vec)/(1 - norm_matrix)
        if flag<eps:
            return x_k
        x_0 = x_k
    return x_k

matrix = np.array([[2, 2, 10, 14],
                   [10, 1, 1, 12],
                   [2, 10, 1, 13]], dtype=float)

A, b = find_coeff(matrix)

print(simple_iter_method(A, b, x_0=b,max_iterations=10000000, eps=1e-6))


[1.00000007 1.00000008 1.0000001 ]


Метод Зейделя

In [35]:
import copy, numpy as np

def find_coeff(M):
    n, _ = M.shape
    for i in range(n):
        maxEl = abs(M[i:, i]).argmax() + i
        if maxEl != i:
            M[[i, maxEl]] = M[[maxEl, i]]
    for i in range(n):
        curr_el = M[i, i]
        M[i] /= -curr_el
        M[i, i] = 0
    A, b = M[:, :n], (-1) * M[:, n]
    return A, b

def seidel_iter_method(A, b, x_0, max_iterations=100, eps=1e-6):
    x_k = copy.deepcopy(x_0)
    for iter in range(max_iterations):
        x_k[iter%len(x_k)] = np.dot(A[iter%len(x_k),:], np.column_stack([x_0])) + b[iter%len(x_k)]
        norm_vec = sum((x_k[i] - x_0[i]) ** 2 for i in range(len(x_k)))**0.5
        norm_matrix = sum((A[i, j])**2 for i in range(A.shape[0]) for j in range(A.shape[1]))**0.5
        flag = (norm_matrix*norm_vec)/(1 - norm_matrix)
        if flag<eps:
            return x_k
        x_0 = copy.deepcopy(x_k)
    return x_k

matrix = np.array([[2, 2, 10, 14],
                   [10, 1, 1, 12],
                   [2, 10, 1, 13]], dtype=float)

A, b = find_coeff(matrix)

print(seidel_iter_method(A, b, x_0=b,max_iterations=10000000, eps=1e-6))

[1.00000013 1.00000016 0.99999816]
