Степенной метод

In [8]:
import numpy as np

def power_iteration(b_k ,A, max_iterations = 100, eps = 1e-6):
    lamb = 0 
    for _ in range(max_iterations):
        b_k1 = np.dot(A, b_k)

        b_k1_norm = np.sqrt(np.sum(b_k1**2))
        lamb_next = b_k1_norm / np.sqrt(np.sum(b_k**2))

        deviation = np.abs(lamb_next - lamb)

        b_k = b_k1 / b_k1_norm

        if deviation < eps:
            break

        lamb = lamb_next

    return lamb, b_k

A = np.array([[5, 1, 2],
              [1, 4, 1],
              [2, 1, 3]])
b_k = np.ones(A.shape[1]) # начальное приближение

eps = 1e-6
max_iterations = 100

self_val, vec = power_iteration(b_k, A, max_iterations, eps)

print("Собственное значение:", self_val)
print("Собственный вектор:", vec)


Собственное значение: 6.895106181094966
Собственный вектор: [0.752536   0.43178113 0.49724704]


Метод вращения

In [15]:
import numpy as np

def rotation(A, max_iterations=100, eps=1e-10):
    n = A.shape[0]
    self_val = np.diag(A)
    vec = np.eye(n)

    for _ in range(max_iterations):
        m_dig = np.abs(A - np.diag(np.diag(A))).max()
        if m_dig < eps:
            break

        max_idx = np.argmax(np.abs(A - np.diag(np.diag(A))))
        p, q = divmod(max_idx, n)

        if A[p, q] == 0:
            beta = np.pi / 4
        else:
            phi = 0.5 * np.arctan(2 * A[p, q] / (A[q, q] - A[p, p]))
            beta = np.sign(phi) * np.pi / 2 - phi

        rotation = np.eye(n)
        rotation[p, p] = np.cos(beta)
        rotation[p, q] = -np.sin(beta)
        rotation[q, p] = np.sin(beta)
        rotation[q, q] = np.cos(beta)

        A = rotation.T @ A @ rotation
        vec = vec @ rotation
        self_val = np.diag(A)

    return self_val, vec

A = np.array([[5, 1, 2],
              [1, 4, 1],
              [2, 1, 3]])
eps = 1e-10
max_iterations = 100

self_val, vec = rotation(A, max_iterations, eps)

print("Собственные значения:")
print(self_val)

print("Собственные векторы:")
print(vec)



Собственные значения:
[1.70759841 6.89510652 3.39729507]
Собственные векторы:
[[ 0.47319874  0.75257583  0.45794385]
 [ 0.17059871  0.43170413 -0.88573564]
 [-0.86427949  0.49725362  0.07589338]]
